### ISSUE TITLE
hwo to set the key when use the BulkInsertOrUpdateAsync methods？

### ISSUE THREAD

**Issue by zsanhong** [cajuncoding/SqlBulkHelpers#1]
if  I have a table have the column Id,key,value, the id is primarykey, but I want to use key column as the merge key,if the key is same,then update,otherwise insert to  the source table.how to do that? thanks!

**Comment by cajuncoding** [comment]
Hmmm well if I’m understanding correctly then that violates data integrity because you could easily end up with the same value updating many records since key is not guaranteed to be unique.

Is there a reason that you don’t have Key as part of your primary key?

It’s likely that you will need to make multiple calls to update & insert to achieve the desired behavior.

I’ve not tried that scenario but you could experiment with using a model that does not have the ID propert at all...so just a Key & Value and see what the desultory merge query looks like.  Off the top of my head I think it will ignore all columns that don’t exit on the model (but I’m not sure if there’s a constraint forcing you to provide the primary key column; there may be).

So you may end up needing to use a custom merge query.  The foundation of this library is to provide support for Models that are uniquely identifiable and to efficiently update them in bulk (vs n+1 performance issues of ORMs) it does not handle all other scenarios that Sql allows.

**Comment by cajuncoding** [comment]
Hmmm not sure if this matches your use case either but you can always process your uniquely identifiable list of items via code (loops/iterate and update using business rules instead of sql).

Then use the library to efficiently persist your data to SqlServer DB...since that’s the original design of the library.

It seems as though you may be using the power is Sql to update your data (Nothing wrong with that) but if it’s the case then a custom merge query is likely where you’ll end up.

Just keep all of that kind of logic encapsulates/isolated/DRY :-)

**Comment by zsanhong** [comment]
thank you,I may change my design of my table to have the unique key as primary
