### ISSUE TITLE
Feature Request: Add support for BIGINT Identity Columns

### ISSUE THREAD

**Issue by pagner** [cajuncoding/SqlBulkHelpers#10]
Currently the library only supports INT identity columns. Would be nice to support BIGINT for different design scenarios. i.e. multi-tenant SAAS applications. GUIDS are another use case, but probably not easy to implement. 

Thanks!

**Comment by cajuncoding** [comment]
Thanks, this is a good idea for feature enhancement. SQL Server does support various integer based numeric data types as `IDENTITY` columns, so it would make sense to support them.

But GUID is not supported as an `IDENTITY` column since it cannot be incremented automatically…this would be a design choice to use a GUID, and there are some significant cons to using it even as a Primary Key, but the application layer would likely generate these therefore `SqlBulkHelpers` would already support this just like it does for any other data type ✅.

**Comment by pagner** [comment]
Sorry I should have described the GUID use case better as a primary key. I was thinking the library could generate relations based on a GUID rather than the identity column. I am seeing this design more frequently as of late in lieu of the identity column. I am guessing that is a can of worms though ;-)

[This framework here](https://abp.io/) uses GUIDS by default instead of identity columns. You can however use int and bigint.

Thanks again for this library. I look forward to future releases.

**Comment by cajuncoding** [comment]
This is now implemented and merged into `main` pending an upcoming release bundled with some other features:
PR: https://github.com/cajuncoding/SqlBulkHelpers/pull/11

**Comment by cajuncoding** [comment]
Now released with https://github.com/cajuncoding/SqlBulkHelpers/releases/tag/v2.2
