### ISSUE TITLE
System.TypeInitializationException thrown when Instantiating SqlBulkIdentityHelper

### ISSUE THREAD

**Issue by cloudb0x** [cajuncoding/SqlBulkHelpers#2]
Throws straight up when newing up the Helper with a TypeInitializationException. Pity.

Inner Exception 

> The application configuration is missing a value for setting [SqlConnectionString], so default Sql Connection cannot be initialized; check the App.config Xml file and try again.

```
                    await using var connection = database.GetConnection();

                    await connection.OpenAsync();

                    await using var transaction = connection.BeginTransaction(IsolationLevel.ReadUncommitted);

                    ISqlBulkHelper<SomeType> sqlBulkIdentityHelper = new SqlBulkIdentityHelper<SomeType>();

                    await sqlBulkIdentityHelper.BulkInsertOrUpdateAsync(myData, "SomeTable", transaction);
```

**Comment by cajuncoding** [comment]
Thank you for your interest in my library!

Yes that exception is expected behavior, and the error message explains exactly what the issue was. By default it uses normal App Configuration to attemp to read the connection string from the configuration key “SqlConnectionString”.

But that is the default behavior. This can be overridden by needing up the `SqlBulkHelpersDBSchemaStaticLoader()`and passing that dependency in. But I’ll admit that I made an opinionated decision to require an `ISqlBulkHelpersConnectionProvider` as a dependency to the DB Schema loader, whereby it has initialized a connection (one time) to load necessary schema details.

So you have two options:
1) Add the connection strings to the application configuration (if using that).
2) Instantiate the Connection provider and the DB schema loader and pass those to the Helper and that should work without any dependency on configuration.

```csharp
//You could put this inside your database class to encapsulate this initialization...
var sqlConnProvider = new SqlBulkHelpersConnectionProvider(connectionString);

var dbSchemaLoader = new SqlBulkHelpersDBSchemaStaticLoader(sqlConnProvider);

ISqlBulkHelper<SomeType> sqlBulkIdentityHelper = new SqlBulkIdentityHelper<SomeType>(dbSchemaLoader);

```

So based on your snippet, you could put this inside your database class to encapsulate it something like database.GetBulkIdentityHelper<T>();

And for performance you would keep the `SqlBulkHelpersDBSchemaStaticLoader` reference statically, or cached, so that it doesn’t ever load a second time (per connection); internally it will Lazy load once and only once until a new instance is created.

Upon reflecting, in my use cases we have DI and repositories wire all this up in one place. But, I can see the value of having an overload to simplify this is you already have the connection/transaction ready...

But I don’t have the time to do this until December.

FYI, you can also check out the awesome RepoDb library...which implements a very similar Bulk Insert approach that I have here...I’m using it on some new projects so it’s worth considering.

Hope this helps!

**Comment by cajuncoding** [comment]
FYI, due to additional incompatibilities with another of our projects, we've now removed the internal static _Default_ instances, which removes all configuraiton dependencies and relies on the consumer to initialize.  We also added better support for initializing directly from a SqlConnection.

So this would likely resolve the issue you experienced and help make correct initialization much more cleaer and explicit.
