### ISSUE TITLE
Fails when there are no identity columns

### ISSUE THREAD

**Issue by SvenVMSW** [cajuncoding/SqlBulkHelpers#3]
When the table does not have an identity column, the SqlBulkHelpersMergeScriptBuilder generates an empty identitycolumn name and it generates the sql for the temporary table as 
SELECT TOP(0) 1 as [{identityColumnName}], 

This gives a SQL exception, maybe skip it or generate a unique name ?

**Comment by cajuncoding** [comment]
I’ll take a look at improving support for vanilla bulk imports so that there’s a consistent approach (api) when using SqlBulkHelpers… 

I’m also going to be optimizing performance so it’ll be probably be part of a slightly bigger release.

**Comment by cajuncoding** [comment]
FYI, the reason this was not included in v1 is because it isn't trivial task to just "turn off" or "skip" the processing of Identity columns without still impacting performance, etc.

But, this has been improved and resolved in the new v2.0 version that is now in pre-release with `beta1`.... 

And it's easier than ever to utilize now with a while new convenience API via custom extensions of the SqlTransaction object...

**Comment by cajuncoding** [comment]
This is fully supported in the pre-release `v2.0-beta1` completed in PR: https://github.com/cajuncoding/SqlBulkHelpers/pull/8

**Comment by cajuncoding** [comment]
V2.0.0 is now released
