### ISSUE TITLE
Dynamic Mapping

### ISSUE THREAD

**Issue by pagner** [cajuncoding/SqlBulkHelpers#9]
Nice library you created here.

I have been looking through the code and there doesn't appear to be a way to dynamically map columns. All of the "Bulk" methods take an IEnumerable as the first argument. I saw where you can decorate the entity properties with a ModelMapping attribute, but what if the mapping isn't know until runtime?

In my case I have a front end client that allows the user to map the columns themselves.

Is there a way to pass in the model mappings at runtime and hook the ColumnMappings.Add() method??

Thanks!

**Comment by pagner** [comment]
Looks like I can use csvhelper to map the columns dynamically before passing to your library. Closing...

**Comment by cajuncoding** [comment]
@pagner Im glad you’re finding the library useful…give it a Star ⭐️ if you use it, it’s free and helps others find it also!

Regarding your question, no the library doesn’t provide its own mechanism for dynamically mapping columns because generally the Database schema and table is known and I like to use best of breed libraries of which there are others that will handle that very efficiently…

The way I would normally handle it would be to define a DB model (and annotation mappings if necessary). Then whatever form your data is coming in as would either be somewhat know via an input model in which case you’d use a well tested solution like `AutoMapper` or more efficient `FastMapper` or `TinyMapper`.

But as your response implied if the incoming data schema is completely unknown — such as customizable CSV format — then whatever parsing mechanism you use would map into the concrete DB schema model.  

I can see a case for adding better support for this in the future but have not had a use case for it yet.

Since you’ve found a solution it would be great if you shared some example code here of how you solved it here for others to find 👍.

**Comment by pagner** [comment]
@cajuncoding Thanks for the prompt reply! I do know one side of the mapping at runtime, which will be the concrete model as you mentioned. The CSV side will be unknown until the user submits the mapping. Data to type validation is performed on the client side. 

I will then use CsvHelper to map the CSV side to the concrete model and then pass if off to your library.

I will post some code when testing is complete.

**Comment by cajuncoding** [comment]
Kewl... let me know how it goes or if you hit a blocker in the library. 👍

**Comment by pagner** [comment]
long (BIGINT) is not supported as an Identity column? 

"Unable to cast object of type 'System.Int64' to type 'System.Int32"

Changed Id in model to int and it works fine. Any reason for this? Just curious, not a deal breaker or blocker.

Thanks,

**Comment by cajuncoding** [comment]
The main reason would be because I’ve never had the use case….since `INT` data type supports over **2.1 billion values** and uses **half** the storage space of BIGINT (4 bytes vs 8), for Identity values it’s nearly always the prudent choice.

**Comment by pagner** [comment]
Gotcha. For testing I had copied my model over from another application. The other application is a SAAS using the soft delete pattern, so using a long there was a design choice. With that said, int is going to be fine in the new application because this data is being stored in a Table per Tenant database for vendor parts lists.

Would it be possible for your library to support long (BIGINT) ? I think you may run into this again.

Thanks.

**Comment by cajuncoding** [comment]
Yeah it could def. be enhanced to support BIGINT per se, it just complicates the scripts that handle the automation a bit, but it could be dynamically resolved pretty easily from the table Schema.

Would be great if you created a new issue “Feature Request” and I’ll try to add support on my next batch of enhancements.

I’ve got some other enhancements slated pretty soon to enable setting Identity values manually for some edge cases we have now and I could possible include this.

**Comment by pagner** [comment]
Will do.. Thanks
